import Link from 'next/link';
import { notFound } from 'next/navigation';
import { ArrowRight, Clock3, Info, MapPin } from 'lucide-react';
import { articles, categories, getArticle, articleHref } from '@/lib/content';
import { ArticleTools } from '@/components/help-ui';
import { GuideScreenshots } from '@/components/guide-screenshots';
import { articleSchema, pageMetadata } from '@/lib/seo';
import { screenshots } from '@/lib/screenshots';
import { StructuredData } from '@/components/structured-data';
export const dynamicParams = false;
export function generateStaticParams() { return articles.map(a => ({ slug: a.slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const a = getArticle(slug); if (!a) notFound(); return pageMetadata(a.title, a.description, `/articles/${slug}`, undefined, 'article'); }
export default async function Article({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const a = getArticle(slug); if (!a) notFound(); const c = categories.find(c => c.slug === a.category)!; return <main id="main" className="container interior"><StructuredData data={articleSchema(a, c)}/><div className="breadcrumbs"><Link href="/">Help Center</Link><span>/</span><Link href={`/topics/${c.slug}`}>{c.title}</Link><span>/</span><span>{a.title}</span></div><div className="article-layout"><aside className="article-sidebar"><span className="small-eyebrow">IN THIS TOPIC</span><h2>{c.title}</h2><nav aria-label="Related topic guides">{articles.filter(item => item.category === c.slug).map(item => <Link aria-current={item.slug === slug ? 'page' : undefined} href={articleHref(item.slug)} key={item.slug}>{item.title}</Link>)}</nav><Link className="sidebar-back" href="/#topics">← All topics</Link></aside><article className="article-body"><span className="small-eyebrow">{c.title}</span><h1>{a.title}</h1><p className="lead">{a.description}</p><div className="read-time"><Clock3 size={15}/> {Math.max(2, Math.ceil(a.steps.join(' ').split(' ').length / 120))} min read <span>·</span> {a.steps.length} steps</div><div className="location"><MapPin size={18}/><div><strong>Where to go</strong><p>{a.path}</p></div></div><h2 id="steps">Step by step</h2><ol className="steps">{a.steps.map((step, i) => <li key={i} id={`step-${i + 1}`}><span>{i+1}</span><p>{step}</p></li>)}</ol><GuideScreenshots slug={a.slug}/>{a.image && <figure><a href={a.image} target="_blank" rel="noreferrer"><img src={a.image} alt={`${a.title}: agency workspace reference`} width="1440" height="900"/></a><figcaption>Workspace reference. Open the image for a closer look.</figcaption></figure>}<div className="callout" id="good-to-know"><Info size={21}/><div><strong>Good to know</strong><p>{a.note}</p></div></div><ArticleTools slug={a.slug}/><section className="related"><h2>Keep going</h2>{a.related.map(slug => { const related = getArticle(slug)!; return <Link href={articleHref(slug)} key={slug}>{related.title}<ArrowRight size={17}/></Link>; })}</section></article></div></main>; }
